steps:
- name: 'gcr.io/cloud-builders/gcloud'
  args:
  - 'functions'
  - 'deploy'
  - '$_FUNCTION_NAME'
  - '--runtime=nodejs16'
  - '--entry-point=gameRunner'
  - '--trigger-http'
  - '--region=us-east1'



substitutions:
  _FUNCTION_NAME: Crabada-mtest
